
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-7pm-4
owner: ucsb-cs156-w24
repo_name: team01-w24-7pm-4
pull_requests: [{"author":{"id":"U_kgDOBXzOLw","is_bot":false,"login":"wesley-hung","name":""},"headRefName":"whung-JokeQueryController","number":22,"title":"[JokeQueryController] Implemented JokeController.java and corresponding tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-4/pull/22"},{"author":{"id":"MDQ6VXNlcjQwNTQ2NDI3","is_bot":false,"login":"viditagrawal","name":""},"headRefName":"viditagrawal-holidayservice-controller","number":21,"title":"[holidayservice] added controller + tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-4/pull/21"},{"author":{"id":"U_kgDOBXux7g","is_bot":false,"login":"wesleytruong","name":""},"headRefName":"wt-LocationQuery","number":19,"title":"Add Location Query Service","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-4/pull/19"}]
