
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-7pm-4
owner: ucsb-cs156-w24
repo_name: team01-w24-7pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ3NTAwNDYw","is_bot":false,"login":"AllenHsm","name":"Allen Hu"},"headRefName":"ah-TidesSvc-Controller","number":24,"title":"Add Tides Query Service and Controller and Their Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-4/pull/24"},{"author":{"id":"MDQ6VXNlcjQ3NTAwNDYw","is_bot":false,"login":"AllenHsm","name":"Allen Hu"},"headRefName":"ah-TidesSvc","number":23,"title":"Add Tides Query Service and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-4/pull/23"},{"author":{"id":"MDQ6VXNlcjQwNTQ2NDI3","is_bot":false,"login":"viditagrawal","name":""},"headRefName":"viditagrawal-holidayservice-controller","number":21,"title":"[holidayservice] added controller + tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-4/pull/21"}]
